export const NOTE_FETCH_REQUEST ='NOTE_FETCH_REQUEST'
export const NOTE_FETCH_SUCCESS ='NOTE_FETCH_SUCCESS'
export const NOTE_FETCH_FAIL ='NOTE_FETCH_FAIL'
export const NOTE_FETCH_RESET ='NOTE_FETCH_RESET'


export const NOTE_ADD_REQUEST ='NOTE_ADD_REQUEST'
export const NOTE_ADD_SUCCESS ='NOTE_ADD_SUCCESS'
export const NOTE_ADD_FAIL ='NOTE_ADD_FAIL'
export const NOTE_ADD_RESET ='NOTE_ADD_RESET'


export const NOTE_UPDATE_REQUEST = "NOTE_UPDATE_REQUEST";
export const NOTE_UPDATE_SUCCESS = "NOTE_UPDATE_SUCCESS";
export const NOTE_UPDATE_FAIL = "NOTE_UPDATE_FAIL";

export const NOTE_DELETE_REQUEST = "NOTE_DELETE_REQUEST";
export const NOTE_DELETE_SUCCESS = "NOTE_DELETE_SUCCESS";
export const NOTE_DELETE_FAIL = "NOTE_DELETE_FAIL";
